### ISSUE TITLE
ImportError: libcfitsio.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lwasser** [conda-forge/rasterio-feedstock#129]
Issue:

When rasterio is imported, I am getting an error as follows:

```
Traceback (most recent call last):
  File "import_check.py", line 3, in <module>
    import rasterio
  File "/opt/conda/lib/python3.7/site-packages/rasterio/__init__.py", line 22, in <module>
    from rasterio._base import gdal_version
ImportError: libcfitsio.so.5: cannot open shared object file: No such file or directory
```
my docker container: https://github.com/earthlab/r-python-eds-lessons-env/blob/master/Dockerfile 

@ocefpaf a few of us have encountered this in the past few days. is this user error or a channel issue? Many thanks. 
<br/>
Environment (<code>conda list</code>):
<details>
https://github.com/earthlab/r-python-eds-lessons-env/blob/master/Dockerfile
```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by ocefpaf** [comment]
Latest `cfitsio` broke the ABI and the workaround for now is to force the old `cfitsio=3.430` in your environment.

We are working on a permanent solution. See https://github.com/regro/cf-scripts/pull/541

**Comment by lwasser** [comment]
got it. i'll try that now. thank you @ocefpaf !!

**Comment by WeatherGod** [comment]
Roughly what is the timeline for having this fixed? Will it be hours, or days? Trying to decide whether to rekick all of my unit tests now with this work-around, or just wait until morning.

**Comment by ocefpaf** [comment]
> or just wait until morning.

It may take 1 day. I'm at SciPy and working on this during the breaks.

**Comment by ocefpaf** [comment]
On Linux it should be fixed. Can you try again and let me know? Still working on other platforms and on a permanent solution (global pin for `cfitsio`).

**Comment by ocefpaf** [comment]
It should be working again for both `proj4 5` and `proj4 6` variants. Please let me know if you find any new issues.

**Comment by WeatherGod** [comment]
still having this issue in very fresh linux conda environments (built a few minutes ago).

**Comment by ocefpaf** [comment]
Looks like only those that uses `proj4 6` got updated correctly :-(

**Comment by ocefpaf** [comment]
Should be OK now. Please let me know if you are still experiencing problems.
