### ISSUE TITLE
rasterio (on conda) segfaults on invalid file (win32/2.7)

### ISSUE THREAD

**Issue by johanvdw** [conda-forge/rasterio-feedstock#44]
on windows the following code causes a segfault with my installation of rasterio (0.36.0):

```
>>> import rasterio
>>> print rasterio.__version__
0.36.0
>>> print rasterio.__gdal_version__
2.1.4
>>> ds = rasterio.open("nonexistingfile")
```

Note that I get this error when importing the normal gdal api:

```
>>> from osgeo import gdal
>>> dataset = gdal.Open("nonexistingfile", gdal.GA_ReadOnly)
ERROR 4: nonexistingfile: No such file or directory
```

On win64 / py 3.6 I don't see this error.
I'm willing to help debugging if someone could give me any pointers.

**Comment by sgillies** [comment]
@johanvdw I'm almost certain this is https://github.com/mapbox/rasterio/issues/935, which was fixed in version 1.0a7.

**Comment by johanvdw** [comment]
Ok,

Actually on linux I also get segfaults when loading invalid files. Eg
```
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rasterio
>>> dst = rasterio.open("invalid.asc")
>>> dst.read(1)
Segmentation fault
```
That seems also solved in version 1.0a10. 

I've attached the file, you should rename to .asc (github does not allow the .asc extension here).
[invalid.asc.txt](https://github.com/conda-forge/rasterio-feedstock/files/1428436/invalid.asc.txt)

**Comment by johanvdw** [comment]
The error still occurs on 1.0a10

![image](https://user-images.githubusercontent.com/868434/32191539-c0228b20-bdb1-11e7-9f94-e151a6599a12.png)

**Comment by ocefpaf** [comment]
@johanvdw looks like an upstream issue and @sgillies seems to be on top of things.

Closing it here.

**Comment by johanvdw** [comment]
I disagree that this issue was closed here:
I just tested python 2.7 with rasterio installed using the wheels provided by https://www.lfd.uci.edu/~gohlke/pythonlibs/#rasterio 
and no errors occur.

On conda windows, 2.7 is not usable as the slightest exception from gdal (eg file does not exist, ...) will crash python (serious impact).

**Comment by johanvdw** [comment]
Correcting myself: the issue (luckily) seems to be resolved by installing the latest rasterio build.
